before_install: sudo apt-get install libicu-dev libmagic-dev -y

language: python

python:
  - "2.6"
  - "2.7"

install:
  - "pip install PyYAML"
  - "pip install -e git+https://github.com/liluo/pygments.git@master#egg=Pygments-1.6"
  - "pip install pygments-github-lexers>=0.0.3"
  - "pip install charlockholmes"
  - "pip install mime>=0.0.3"

branches:
  only:
    - master

script:
  - "cd tests"
  - "python run.py"
