before_install: sudo apt-get install libicu-dev libmagic-dev -y

language: python

python:
  - "2.6"
  - "2.7"

install:
  - "pip install PyYAML"
  - "pip install pygments>=1.6"
  - "pip install pygments-github-lexers>=0.01"
  - "pip install charlockholmes"
  - "pip install mime>=0.02"

branches:
  only:
    - master

script:
  - "cd tests"
  - "python run.py"
